import { ScrapCategory } from '../types/rateCard';

export const SCRAP_CATEGORIES: ScrapCategory[] = [
  // Paper & Cardboard
  {
    id: 'paper-newspaper',
    name: 'Newspaper',
    name_hindi: 'अखबार',
    name_odia: 'ଖବର କାଗଜ',
    name_marathi: 'वर्तमानपत्र',
    name_tamil: 'செய்தித்தாள்',
    name_telugu: 'వార్తాపత్రిక',
    name_kannada: 'ಪತ್ರಿಕೆ',
    icon: '📰',
    parent_id: 'paper',
    description: 'Old newspapers and magazines',
    unit: 'kg',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'paper-cardboard',
    name: 'Cardboard',
    name_hindi: 'गत्ता',
    name_odia: 'କାର୍ଡବୋର୍ଡ',
    name_marathi: 'पुठ्ठा',
    name_tamil: 'அட்டை',
    name_telugu: 'కార్డ్‌బోర్డ్',
    name_kannada: 'ಕಾರ್ಡ್‌ಬೋರ್ಡ್',
    icon: '📦',
    parent_id: 'paper',
    description: 'Cardboard boxes and packaging',
    unit: 'kg',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'paper-books',
    name: 'Books / Copies',
    name_hindi: 'किताबें / कॉपी',
    name_odia: 'ବହି / କପି',
    name_marathi: 'पुस्तके / वह्या',
    name_tamil: 'புத்தகங்கள்',
    name_telugu: 'పుస్తకాలు',
    name_kannada: 'ಪುಸ್ತಕಗಳು',
    icon: '📚',
    parent_id: 'paper',
    description: 'Old books, notebooks, and copies',
    unit: 'kg',
    is_active: true,
    sort_order: 3,
  },

  // Metals
  {
    id: 'metal-iron',
    name: 'Iron',
    name_hindi: 'लोहा',
    name_odia: 'ଲୁହା',
    name_marathi: 'लोखंड',
    name_tamil: 'இரும்பு',
    name_telugu: 'ఇనుము',
    name_kannada: 'ಕಬ್ಬಿಣ',
    icon: '🔩',
    parent_id: 'metal',
    description: 'Iron and steel items',
    unit: 'kg',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'metal-aluminium',
    name: 'Aluminium',
    name_hindi: 'एल्युमिनियम',
    name_odia: 'ଆଲୁମିନିୟମ',
    name_marathi: 'अॅल्युमिनियम',
    name_tamil: 'அலுமினியம்',
    name_telugu: 'అల్యూమినియం',
    name_kannada: 'ಅಲ್ಯೂಮಿನಿಯಂ',
    icon: '🥫',
    parent_id: 'metal',
    description: 'Aluminium cans, foil, and items',
    unit: 'kg',
    is_active: true,
    sort_order: 5,
  },
  {
    id: 'metal-copper',
    name: 'Copper',
    name_hindi: 'तांबा',
    name_odia: 'ତମ୍ବା',
    name_marathi: 'तांबे',
    name_tamil: 'செம்பு',
    name_telugu: 'రాగి',
    name_kannada: 'ತಾಮ್ರ',
    icon: '🔌',
    parent_id: 'metal',
    description: 'Copper wires and items',
    unit: 'kg',
    is_active: true,
    sort_order: 6,
  },
  {
    id: 'metal-brass',
    name: 'Brass',
    name_hindi: 'पीतल',
    name_odia: 'ପିତ୍ତଳ',
    name_marathi: 'पितळ',
    name_tamil: 'பித்தளை',
    name_telugu: 'ఇత్తడి',
    name_kannada: 'ಹಿತ್ತಾಳೆ',
    icon: '🔔',
    parent_id: 'metal',
    description: 'Brass utensils and items',
    unit: 'kg',
    is_active: true,
    sort_order: 7,
  },

  // Plastic
  {
    id: 'plastic-bottles',
    name: 'Plastic Bottles',
    name_hindi: 'प्लास्टिक बोतल',
    name_odia: 'ପ୍ଲାଷ୍ଟିକ ବୋତଲ',
    name_marathi: 'प्लास्टिक बाटल्या',
    name_tamil: 'பிளாஸ்டிக் பாட்டில்',
    name_telugu: 'ప్లాస్టిక్ బాటిల్',
    name_kannada: 'ಪ್ಲಾಸ್ಟಿಕ್ ಬಾಟಲಿ',
    icon: '🧴',
    parent_id: 'plastic',
    description: 'PET bottles and containers',
    unit: 'kg',
    is_active: true,
    sort_order: 8,
  },
  {
    id: 'plastic-hard',
    name: 'Hard Plastic',
    name_hindi: 'कड़ा प्लास्टिक',
    name_odia: 'କଠିନ ପ୍ଲାଷ୍ଟିକ',
    name_marathi: 'कडक प्लास्टिक',
    name_tamil: 'கடின பிளாஸ்டிக்',
    name_telugu: 'గట్టి ప్లాస్టిక్',
    name_kannada: 'ಗಟ್ಟಿ ಪ್ಲಾಸ್ಟಿಕ್',
    icon: '🪣',
    parent_id: 'plastic',
    description: 'Buckets, chairs, and hard plastic',
    unit: 'kg',
    is_active: true,
    sort_order: 9,
  },
  {
    id: 'plastic-soft',
    name: 'Soft Plastic / Covers',
    name_hindi: 'पॉलीथीन',
    name_odia: 'ପଲିଥିନ',
    name_marathi: 'पॉलिथीन',
    name_tamil: 'பாலிதீன்',
    name_telugu: 'పాలిథీన్',
    name_kannada: 'ಪಾಲಿಥೀನ್',
    icon: '🛍️',
    parent_id: 'plastic',
    description: 'Polythene bags and soft plastic',
    unit: 'kg',
    is_active: true,
    sort_order: 10,
  },

  // Glass
  {
    id: 'glass-bottles',
    name: 'Glass Bottles',
    name_hindi: 'कांच की बोतलें',
    name_odia: 'କାଚ ବୋତଲ',
    name_marathi: 'काचेच्या बाटल्या',
    name_tamil: 'கண்ணாடி பாட்டில்',
    name_telugu: 'గాజు బాటిల్',
    name_kannada: 'ಗಾಜಿನ ಬಾಟಲಿ',
    icon: '🍾',
    parent_id: 'glass',
    description: 'Glass bottles and jars',
    unit: 'kg',
    is_active: true,
    sort_order: 11,
  },

  // E-waste
  {
    id: 'ewaste-mobile',
    name: 'Old Mobile Phones',
    name_hindi: 'पुराना मोबाइल',
    name_odia: 'ପୁରୁଣା ମୋବାଇଲ',
    name_marathi: 'जुना मोबाइल',
    name_tamil: 'பழைய மொபைல்',
    name_telugu: 'పాత మొబైల్',
    name_kannada: 'ಹಳೆ ಮೊಬೈಲ್',
    icon: '📱',
    parent_id: 'ewaste',
    description: 'Old or broken mobile phones',
    unit: 'piece',
    is_active: true,
    sort_order: 12,
  },
  {
    id: 'ewaste-laptop',
    name: 'Laptops / Computers',
    name_hindi: 'लैपटॉप / कंप्यूटर',
    name_odia: 'ଲ୍ୟାପଟପ / କମ୍ପ୍ୟୁଟର',
    name_marathi: 'लॅपटॉप / कॉम्प्युटर',
    name_tamil: 'லேப்டாப் / கணினி',
    name_telugu: 'ల్యాప్‌టాప్ / కంప్యూటర్',
    name_kannada: 'ಲ್ಯಾಪ್‌ಟಾಪ್ / ಕಂಪ್ಯೂಟರ್',
    icon: '💻',
    parent_id: 'ewaste',
    description: 'Old laptops, desktops, and parts',
    unit: 'piece',
    is_active: true,
    sort_order: 13,
  },
  {
    id: 'ewaste-appliances',
    name: 'Small Appliances',
    name_hindi: 'छोटे उपकरण',
    name_odia: 'ଛୋଟ ଉପକରଣ',
    name_marathi: 'लहान उपकरणे',
    name_tamil: 'சிறிய சாதனங்கள்',
    name_telugu: 'చిన్న ఉపకరణాలు',
    name_kannada: 'ಸಣ್ಣ ಉಪಕರಣಗಳು',
    icon: '🔌',
    parent_id: 'ewaste',
    description: 'Mixers, irons, fans, etc.',
    unit: 'piece',
    is_active: true,
    sort_order: 14,
  },
  {
    id: 'ewaste-batteries',
    name: 'Batteries',
    name_hindi: 'बैटरी',
    name_odia: 'ବ୍ୟାଟେରୀ',
    name_marathi: 'बॅटरी',
    name_tamil: 'பேட்டரி',
    name_telugu: 'బ్యాటరీ',
    name_kannada: 'ಬ್ಯಾಟರಿ',
    icon: '🔋',
    parent_id: 'ewaste',
    description: 'All types of batteries',
    unit: 'kg',
    is_active: true,
    sort_order: 15,
  },

  // Miscellaneous
  {
    id: 'misc-clothes',
    name: 'Old Clothes',
    name_hindi: 'पुराने कपड़े',
    name_odia: 'ପୁରୁଣା ଲୁଗା',
    name_marathi: 'जुने कपडे',
    name_tamil: 'பழைய ஆடை',
    name_telugu: 'పాత బట్టలు',
    name_kannada: 'ಹಳೆ ಬಟ್ಟೆ',
    icon: '👕',
    parent_id: 'misc',
    description: 'Old clothes and fabric',
    unit: 'kg',
    is_active: true,
    sort_order: 16,
  },
  {
    id: 'misc-tyres',
    name: 'Rubber / Tyres',
    name_hindi: 'रबर / टायर',
    name_odia: 'ରବର / ଟାୟାର',
    name_marathi: 'रबर / टायर',
    name_tamil: 'ரப்பர் / டயர்',
    name_telugu: 'రబ్బర్ / టైర్',
    name_kannada: 'ರಬ್ಬರ್ / ಟೈರ್',
    icon: '🛞',
    parent_id: 'misc',
    description: 'Old tyres and rubber items',
    unit: 'kg',
    is_active: true,
    sort_order: 17,
  },
];

// Parent categories for grouping
export const SCRAP_PARENT_CATEGORIES = [
  { id: 'paper', name: 'Paper & Cardboard', name_hindi: 'कागज और गत्ता', name_odia: 'କାଗଜ ଓ ଗତ୍ତା', name_marathi: 'कागद आणि पुठ्ठा', name_tamil: 'காகிதம்', name_telugu: 'కాగితం', name_kannada: 'ಕಾಗದ', icon: '📄' },
  { id: 'metal', name: 'Metals', name_hindi: 'धातु', name_odia: 'ଧାତୁ', name_marathi: 'धातू', name_tamil: 'உலோகம்', name_telugu: 'లోహం', name_kannada: 'ಲೋಹ', icon: '🔧' },
  { id: 'plastic', name: 'Plastic', name_hindi: 'प्लास्टिक', name_odia: 'ପ୍ଲାଷ୍ଟିକ', name_marathi: 'प्लास्टिक', name_tamil: 'பிளாஸ்டிக்', name_telugu: 'ప్లాస్టిక్', name_kannada: 'ಪ್ಲಾಸ್ಟಿಕ್', icon: '♻️' },
  { id: 'glass', name: 'Glass', name_hindi: 'कांच', name_odia: 'କାଚ', name_marathi: 'काच', name_tamil: 'கண்ணாடி', name_telugu: 'గాజు', name_kannada: 'ಗಾಜು', icon: '🪟' },
  { id: 'ewaste', name: 'E-Waste', name_hindi: 'ई-कचरा', name_odia: 'ଇ-ବର୍ଜ୍ୟ', name_marathi: 'ई-कचरा', name_tamil: 'மின்-கழிவு', name_telugu: 'ఈ-వేస్ట్', name_kannada: 'ಇ-ತ್ಯಾಜ್ಯ', icon: '🖥️' },
  { id: 'misc', name: 'Miscellaneous', name_hindi: 'अन्य', name_odia: 'ଅନ୍ୟାନ୍ୟ', name_marathi: 'इतर', name_tamil: 'இதர', name_telugu: 'ఇతరం', name_kannada: 'ಇತರೆ', icon: '📦' },
] as const;

// Default rates per kg (in INR) - will be managed via admin
export const DEFAULT_RATES: Record<string, number> = {
  'paper-newspaper': 14,
  'paper-cardboard': 8,
  'paper-books': 12,
  'metal-iron': 28,
  'metal-aluminium': 105,
  'metal-copper': 425,
  'metal-brass': 305,
  'plastic-bottles': 10,
  'plastic-hard': 15,
  'plastic-soft': 5,
  'glass-bottles': 3,
  'ewaste-mobile': 50,    // per piece
  'ewaste-laptop': 200,   // per piece
  'ewaste-appliances': 25, // per piece
  'ewaste-batteries': 60,
  'misc-clothes': 2,
  'misc-tyres': 8,
};
