import { ScrapCategory } from '../types/rateCard';

export const SCRAP_CATEGORIES: ScrapCategory[] = [
  // Paper & Cardboard
  {
    id: 'paper-newspaper',
    name: 'Newspaper',
    name_hindi: 'अखबार',
    icon: '📰',
    parent_id: 'paper',
    description: 'Old newspapers and magazines',
    unit: 'kg',
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'paper-cardboard',
    name: 'Cardboard',
    name_hindi: 'गत्ता',
    icon: '📦',
    parent_id: 'paper',
    description: 'Cardboard boxes and packaging',
    unit: 'kg',
    is_active: true,
    sort_order: 2,
  },
  {
    id: 'paper-books',
    name: 'Books / Copies',
    name_hindi: 'किताबें / कॉपी',
    icon: '📚',
    parent_id: 'paper',
    description: 'Old books, notebooks, and copies',
    unit: 'kg',
    is_active: true,
    sort_order: 3,
  },

  // Metals
  {
    id: 'metal-iron',
    name: 'Iron',
    name_hindi: 'लोहा',
    icon: '🔩',
    parent_id: 'metal',
    description: 'Iron and steel items',
    unit: 'kg',
    is_active: true,
    sort_order: 4,
  },
  {
    id: 'metal-aluminium',
    name: 'Aluminium',
    name_hindi: 'एल्युमिनियम',
    icon: '🥫',
    parent_id: 'metal',
    description: 'Aluminium cans, foil, and items',
    unit: 'kg',
    is_active: true,
    sort_order: 5,
  },
  {
    id: 'metal-copper',
    name: 'Copper',
    name_hindi: 'तांबा',
    icon: '🔌',
    parent_id: 'metal',
    description: 'Copper wires and items',
    unit: 'kg',
    is_active: true,
    sort_order: 6,
  },
  {
    id: 'metal-brass',
    name: 'Brass',
    name_hindi: 'पीतल',
    icon: '🔔',
    parent_id: 'metal',
    description: 'Brass utensils and items',
    unit: 'kg',
    is_active: true,
    sort_order: 7,
  },

  // Plastic
  {
    id: 'plastic-bottles',
    name: 'Plastic Bottles',
    name_hindi: 'प्लास्टिक बोतल',
    icon: '🧴',
    parent_id: 'plastic',
    description: 'PET bottles and containers',
    unit: 'kg',
    is_active: true,
    sort_order: 8,
  },
  {
    id: 'plastic-hard',
    name: 'Hard Plastic',
    name_hindi: 'कड़ा प्लास्टिक',
    icon: '🪣',
    parent_id: 'plastic',
    description: 'Buckets, chairs, and hard plastic',
    unit: 'kg',
    is_active: true,
    sort_order: 9,
  },
  {
    id: 'plastic-soft',
    name: 'Soft Plastic / Covers',
    name_hindi: 'पॉलीथीन',
    icon: '🛍️',
    parent_id: 'plastic',
    description: 'Polythene bags and soft plastic',
    unit: 'kg',
    is_active: true,
    sort_order: 10,
  },

  // Glass
  {
    id: 'glass-bottles',
    name: 'Glass Bottles',
    name_hindi: 'कांच की बोतलें',
    icon: '🍾',
    parent_id: 'glass',
    description: 'Glass bottles and jars',
    unit: 'kg',
    is_active: true,
    sort_order: 11,
  },

  // E-waste
  {
    id: 'ewaste-mobile',
    name: 'Old Mobile Phones',
    name_hindi: 'पुराना मोबाइल',
    icon: '📱',
    parent_id: 'ewaste',
    description: 'Old or broken mobile phones',
    unit: 'piece',
    is_active: true,
    sort_order: 12,
  },
  {
    id: 'ewaste-laptop',
    name: 'Laptops / Computers',
    name_hindi: 'लैपटॉप / कंप्यूटर',
    icon: '💻',
    parent_id: 'ewaste',
    description: 'Old laptops, desktops, and parts',
    unit: 'piece',
    is_active: true,
    sort_order: 13,
  },
  {
    id: 'ewaste-appliances',
    name: 'Small Appliances',
    name_hindi: 'छोटे उपकरण',
    icon: '🔌',
    parent_id: 'ewaste',
    description: 'Mixers, irons, fans, etc.',
    unit: 'piece',
    is_active: true,
    sort_order: 14,
  },
  {
    id: 'ewaste-batteries',
    name: 'Batteries',
    name_hindi: 'बैटरी',
    icon: '🔋',
    parent_id: 'ewaste',
    description: 'All types of batteries',
    unit: 'kg',
    is_active: true,
    sort_order: 15,
  },

  // Miscellaneous
  {
    id: 'misc-clothes',
    name: 'Old Clothes',
    name_hindi: 'पुराने कपड़े',
    icon: '👕',
    parent_id: 'misc',
    description: 'Old clothes and fabric',
    unit: 'kg',
    is_active: true,
    sort_order: 16,
  },
  {
    id: 'misc-tyres',
    name: 'Rubber / Tyres',
    name_hindi: 'रबर / टायर',
    icon: '🛞',
    parent_id: 'misc',
    description: 'Old tyres and rubber items',
    unit: 'kg',
    is_active: true,
    sort_order: 17,
  },
];

// Parent categories for grouping
export const SCRAP_PARENT_CATEGORIES = [
  { id: 'paper', name: 'Paper & Cardboard', name_hindi: 'कागज और गत्ता', icon: '📄' },
  { id: 'metal', name: 'Metals', name_hindi: 'धातु', icon: '🔧' },
  { id: 'plastic', name: 'Plastic', name_hindi: 'प्लास्टिक', icon: '♻️' },
  { id: 'glass', name: 'Glass', name_hindi: 'कांच', icon: '🪟' },
  { id: 'ewaste', name: 'E-Waste', name_hindi: 'ई-कचरा', icon: '🖥️' },
  { id: 'misc', name: 'Miscellaneous', name_hindi: 'अन्य', icon: '📦' },
] as const;

// Default rates per kg (in INR) - will be managed via admin
export const DEFAULT_RATES: Record<string, number> = {
  'paper-newspaper': 14,
  'paper-cardboard': 8,
  'paper-books': 12,
  'metal-iron': 28,
  'metal-aluminium': 105,
  'metal-copper': 425,
  'metal-brass': 305,
  'plastic-bottles': 10,
  'plastic-hard': 15,
  'plastic-soft': 5,
  'glass-bottles': 3,
  'ewaste-mobile': 50,    // per piece
  'ewaste-laptop': 200,   // per piece
  'ewaste-appliances': 25, // per piece
  'ewaste-batteries': 60,
  'misc-clothes': 2,
  'misc-tyres': 8,
};
