[build]
  base = "apps/admin"
  command = "cd ../../ && pnpm install --no-frozen-lockfile && cd apps/admin && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
